In [3]:
import pandas as pd
from sklearn.datasets import load_iris

# Load the famous Iris dataset
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Quick check
print("Shape:", df.shape)
display(df.head())

Shape: (150, 5)


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [4]:
# Step 1: Data Exploration and Info
print("Dataset Info:")
print(df.info())
print("\n" + "="*50)
print("Statistical Summary:")
print(df.describe())
print("\n" + "="*50)
print("Missing Values:")
print(df.isnull().sum())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None

Statistical Summary:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%           

In [5]:
# Step 2: Separate Features (X) and Target (y)
X = df.drop('target', axis=1)  # Features
y = df['target']  # Target variable

print("Features shape:", X.shape)
print("Target shape:", y.shape)
print("\nTarget distribution:")
print(y.value_counts().sort_index())

Features shape: (150, 4)
Target shape: (150,)

Target distribution:
target
0    50
1    50
2    50
Name: count, dtype: int64


In [6]:
# Step 3: Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,  # 80-20 split
    random_state=42,  # For reproducibility
    stratify=y  # Maintain class distribution
)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)
print("\nTarget distribution in training set:")
print(y_train.value_counts().sort_index())
print("\nTarget distribution in test set:")
print(y_test.value_counts().sort_index())

Training set size: (120, 4)
Test set size: (30, 4)

Target distribution in training set:
target
0    40
1    40
2    40
Name: count, dtype: int64

Target distribution in test set:
target
0    10
1    10
2    10
Name: count, dtype: int64


In [7]:
# Step 4: Train Random Forest Model
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=50,  # Number of trees
    random_state=42,
    n_jobs=-1  # Use all available processors
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest Model trained successfully!")
print("Number of trees:", rf_model.n_estimators)
print("Feature importances:")
for feature, importance in zip(X.columns, rf_model.feature_importances_):
    print(f"  {feature}: {importance:.4f}")

Random Forest Model trained successfully!
Number of trees: 50
Feature importances:
  sepal length (cm): 0.1148
  sepal width (cm): 0.0143
  petal length (cm): 0.4306
  petal width (cm): 0.4404


In [8]:
# Step 5: Model Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import numpy as np

# Make predictions
y_train_pred = rf_model.predict(X_train)
y_test_pred = rf_model.predict(X_test)

# Calculate metrics
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("="*50)
print("MODEL PERFORMANCE")
print("="*50)
print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")
print("\n" + "="*50)
print("CLASSIFICATION REPORT (Test Set)")
print("="*50)
print(classification_report(y_test, y_test_pred, target_names=iris.target_names))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

MODEL PERFORMANCE
Training Accuracy: 1.0000
Test Accuracy: 0.9000

CLASSIFICATION REPORT (Test Set)
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.82      0.90      0.86        10
   virginica       0.89      0.80      0.84        10

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30


Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]
